import type { RenterLanguage } from "./session";

const COPY = {
  en: {
    "app.subtitle": "Simple help for your rental",
    "app.exit": "Exit renter view",
    "home.title": "Your rental machines",
    "home.subtitle": "Choose the machine you’re using. Read the notes first, then ask if anything is unclear.",
    "home.loading": "Loading your rental machines…",
    "home.empty": "No rental machines are available right now. Check with your rental team.",
    "machine.type.dozer": "dozer",
    "machine.type.excavator": "excavator",
    "machine.type.wheel_loader": "wheel loader",
    "machine.reviewNotes": "Review notes",
    "machine.noAlerts": "No current alerts",
    "machine.readBeforeStart": "There are machine notes to read before you start.",
    "machine.openGuide": "Open the machine guide for recent notes and help.",
    "machine.open": "Open machine guide →",
    "machine.serial": "Serial",
    "machine.back": "All machines",
    "before.title": "Before you start",
    "before.safetyWarning": "Safety warning",
    "before.stop": "Stop and check with your rental team or site supervisor before continuing.",
    "before.alert": "Machine alert",
    "before.alertSummary": "A saved alert needs your attention.",
    "before.askAlert": "Ask below what it means. If you’re unsure, check with the rental team before continuing.",
    "before.details": "View machine details",
    "before.checkedShop": "Checked by shop",
    "before.operatorReport": "Reported by an operator",
    "before.rentalTeam": "Rental team note",
    "before.machineNote": "Machine note",
    "before.empty": "No machine-specific notes are available. Follow the rental team’s instructions and ask them if anything feels wrong.",
    "before.safetyRules": "Safety rules",
    "before.noSafetyRules": "No machine-specific safety rules are saved here. Follow the machine’s operator manual and your rental team’s instructions. Stop and ask for help if the machine behaves unexpectedly.",
    "before.askIfUnsure": "If you’re unsure, stop and contact your rental team or site supervisor.",
    "before.noteEnglish": "Saved note (English)",
    "before.alertEnglish": "Machine alert (English)",
    "ask.title": "Ask this machine",
    "ask.subtitle": "Ask a question in your own words. Answers use saved machine information.",
    "ask.language": "Language",
    "ask.experience": "Experience",
    "ask.firstTime": "First time",
    "ask.someExperience": "Some experience",
    "ask.experienced": "Experienced",
    "ask.readAloud": "Read answers aloud",
    "ask.try": "Ask about a warning, a machine note, or what to check before you start.",
    "ask.checking": "Checking this machine’s saved information…",
    "ask.finding": "Finding an answer…",
    "ask.placeholder": "e.g. What does this warning mean?",
    "ask.voice": "Ask using your voice",
    "ask.stopVoice": "Stop voice input",
    "ask.button": "Ask",
    "ask.voiceUnsupported": "Voice input isn’t supported in this browser. Type your question instead.",
    "ask.voiceError": "We couldn’t hear that. Please try again or type your question.",
    "ask.greeting": "Hi! I can help with saved information about this machine. What would you like to know? For example, ask about a warning light or a recent service note.",
    "ask.thanks": "You’re welcome! Ask me about a warning or a note saved for this machine whenever you’re ready.",
    "ask.clarify": "What would you like to know about “{question}”? Try asking a complete question, such as “What does this warning mean?” or “What do the service notes say?”",
    "ask.savedNote": "The saved machine note says: {note} This note is in English. If it doesn’t answer your question, check with your rental team.",
    "ask.alertUnclear": "I found a machine alert that may relate to your question, but I can’t explain it reliably from the saved information. Please check with your rental team before continuing.",
    "ask.notFound": "I couldn’t find saved information about “{question}” for this machine. The records I found don’t mention it. Please ask your rental team what to do rather than guessing.",
  },
  es: {
    "app.subtitle": "Ayuda sencilla para tu alquiler",
    "app.exit": "Salir de la vista de alquiler",
    "home.title": "Tus máquinas de alquiler",
    "home.subtitle": "Elige la máquina que vas a usar. Lee las notas primero y pregunta si algo no está claro.",
    "home.loading": "Cargando tus máquinas de alquiler…",
    "home.empty": "No hay máquinas de alquiler disponibles ahora. Consulta con el equipo de alquiler.",
    "machine.type.dozer": "topadora",
    "machine.type.excavator": "excavadora",
    "machine.type.wheel_loader": "cargadora de ruedas",
    "machine.reviewNotes": "Revisa las notas",
    "machine.noAlerts": "Sin alertas actuales",
    "machine.readBeforeStart": "Lee las notas de la máquina antes de empezar.",
    "machine.openGuide": "Abre la guía para ver notas recientes y obtener ayuda.",
    "machine.open": "Abrir guía de la máquina →",
    "machine.serial": "Serie",
    "machine.back": "Todas las máquinas",
    "before.title": "Antes de empezar",
    "before.safetyWarning": "Advertencia de seguridad",
    "before.stop": "Detente y consulta con el equipo de alquiler o el supervisor antes de continuar.",
    "before.alert": "Alerta de la máquina",
    "before.alertSummary": "Hay una alerta guardada que requiere tu atención.",
    "before.askAlert": "Pregunta abajo qué significa. Si no estás seguro, consulta con el equipo de alquiler antes de continuar.",
    "before.details": "Ver detalles de la máquina",
    "before.checkedShop": "Revisado por el taller",
    "before.operatorReport": "Aviso de un operador",
    "before.rentalTeam": "Nota del equipo de alquiler",
    "before.machineNote": "Nota de la máquina",
    "before.empty": "No hay notas específicas de esta máquina. Sigue las instrucciones del equipo de alquiler y consúltales si algo parece estar mal.",
    "before.safetyRules": "Reglas de seguridad",
    "before.noSafetyRules": "No hay reglas de seguridad específicas guardadas aquí. Sigue el manual de la máquina y las instrucciones del equipo de alquiler. Detente y pide ayuda si la máquina se comporta de forma inesperada.",
    "before.askIfUnsure": "Si no estás seguro, detente y comunícate con el equipo de alquiler o el supervisor.",
    "before.noteEnglish": "Nota guardada (en inglés)",
    "before.alertEnglish": "Alerta de la máquina (en inglés)",
    "ask.title": "Pregunta a esta máquina",
    "ask.subtitle": "Haz una pregunta con tus propias palabras. Las respuestas usan información guardada de la máquina.",
    "ask.language": "Idioma",
    "ask.experience": "Experiencia",
    "ask.firstTime": "Primera vez",
    "ask.someExperience": "Algo de experiencia",
    "ask.experienced": "Con experiencia",
    "ask.readAloud": "Leer respuestas en voz alta",
    "ask.try": "Pregunta sobre una luz de advertencia, una nota de la máquina o qué revisar antes de empezar.",
    "ask.checking": "Buscando información guardada de esta máquina…",
    "ask.finding": "Buscando una respuesta…",
    "ask.placeholder": "p. ej., ¿Qué significa esta advertencia?",
    "ask.voice": "Preguntar con la voz",
    "ask.stopVoice": "Detener entrada de voz",
    "ask.button": "Preguntar",
    "ask.voiceUnsupported": "Este navegador no admite entrada de voz. Escribe tu pregunta.",
    "ask.voiceError": "No pudimos oírte. Inténtalo de nuevo o escribe tu pregunta.",
    "ask.greeting": "¡Hola! Puedo ayudarte con la información guardada de esta máquina. ¿Qué quieres saber? Por ejemplo, pregunta sobre una luz de advertencia o una nota de servicio reciente.",
    "ask.thanks": "¡De nada! Cuando quieras, pregúntame sobre una advertencia o una nota guardada de esta máquina.",
    "ask.clarify": "¿Qué quieres saber sobre “{question}”? Intenta hacer una pregunta completa, como “¿Qué significa esta advertencia?” o “¿Qué dicen las notas de servicio?”",
    "ask.savedNote": "La nota guardada de la máquina dice: {note} Esta nota está en inglés. Si no responde a tu pregunta, consulta con el equipo de alquiler.",
    "ask.alertUnclear": "Encontré una alerta que podría estar relacionada, pero no puedo explicarla con seguridad usando la información guardada. Consulta con el equipo de alquiler antes de continuar.",
    "ask.notFound": "No encontré información guardada sobre “{question}” para esta máquina. Los registros disponibles no lo mencionan. Pregunta al equipo de alquiler qué hacer en vez de adivinar.",
  },
  fr: {
    "app.subtitle": "Une aide simple pour votre location",
    "app.exit": "Quitter la vue locataire",
    "home.title": "Vos machines de location",
    "home.subtitle": "Choisissez la machine que vous utilisez. Lisez d’abord les notes et posez vos questions si besoin.",
    "home.loading": "Chargement de vos machines de location…",
    "home.empty": "Aucune machine de location n’est disponible pour le moment. Contactez l’équipe de location.",
    "machine.type.dozer": "bulldozer",
    "machine.type.excavator": "pelle",
    "machine.type.wheel_loader": "chargeuse sur pneus",
    "machine.reviewNotes": "Consulter les notes",
    "machine.noAlerts": "Aucune alerte actuelle",
    "machine.readBeforeStart": "Consultez les notes de la machine avant de commencer.",
    "machine.openGuide": "Ouvrez le guide pour consulter les notes récentes et obtenir de l’aide.",
    "machine.open": "Ouvrir le guide de la machine →",
    "machine.serial": "Nº de série",
    "machine.back": "Toutes les machines",
    "before.title": "Avant de commencer",
    "before.safetyWarning": "Avertissement de sécurité",
    "before.stop": "Arrêtez-vous et contactez l’équipe de location ou le responsable du site avant de continuer.",
    "before.alert": "Alerte machine",
    "before.alertSummary": "Une alerte enregistrée nécessite votre attention.",
    "before.askAlert": "Demandez ci-dessous ce que cela signifie. En cas de doute, contactez l’équipe de location avant de continuer.",
    "before.details": "Voir les détails de la machine",
    "before.checkedShop": "Vérifié par l’atelier",
    "before.operatorReport": "Signalé par un opérateur",
    "before.rentalTeam": "Note de l’équipe de location",
    "before.machineNote": "Note sur la machine",
    "before.empty": "Aucune note spécifique à cette machine n’est disponible. Suivez les consignes de l’équipe de location et contactez-la si quelque chose semble anormal.",
    "before.safetyRules": "Règles de sécurité",
    "before.noSafetyRules": "Aucune règle de sécurité spécifique n’est enregistrée ici. Suivez le manuel de la machine et les consignes de l’équipe de location. Arrêtez-vous et demandez de l’aide si la machine se comporte de façon inattendue.",
    "before.askIfUnsure": "En cas de doute, arrêtez-vous et contactez l’équipe de location ou le responsable du site.",
    "before.noteEnglish": "Note enregistrée (en anglais)",
    "before.alertEnglish": "Alerte machine (en anglais)",
    "ask.title": "Demander à cette machine",
    "ask.subtitle": "Posez votre question avec vos propres mots. Les réponses s’appuient sur les informations enregistrées pour cette machine.",
    "ask.language": "Langue",
    "ask.experience": "Expérience",
    "ask.firstTime": "Première fois",
    "ask.someExperience": "Un peu d’expérience",
    "ask.experienced": "Expérimenté",
    "ask.readAloud": "Lire les réponses à voix haute",
    "ask.try": "Posez une question sur un voyant, une note de la machine ou les vérifications à faire avant de commencer.",
    "ask.checking": "Recherche des informations enregistrées sur cette machine…",
    "ask.finding": "Recherche d’une réponse…",
    "ask.placeholder": "Ex. : Que signifie cet avertissement ?",
    "ask.voice": "Poser une question à voix haute",
    "ask.stopVoice": "Arrêter la saisie vocale",
    "ask.button": "Demander",
    "ask.voiceUnsupported": "La saisie vocale n’est pas prise en charge par ce navigateur. Saisissez votre question.",
    "ask.voiceError": "Nous n’avons pas compris. Réessayez ou saisissez votre question.",
    "ask.greeting": "Bonjour ! Je peux vous aider avec les informations enregistrées sur cette machine. Que souhaitez-vous savoir ? Vous pouvez poser une question sur un voyant ou une note d’entretien récente.",
    "ask.thanks": "Avec plaisir ! Vous pouvez me poser une question sur un avertissement ou une note enregistrée pour cette machine.",
    "ask.clarify": "Que souhaitez-vous savoir à propos de « {question} » ? Essayez une question complète, par exemple : « Que signifie cet avertissement ? » ou « Que disent les notes d’entretien ? »",
    "ask.savedNote": "La note enregistrée sur la machine indique : {note} Cette note est en anglais. Si elle ne répond pas à votre question, contactez l’équipe de location.",
    "ask.alertUnclear": "J’ai trouvé une alerte qui pourrait être liée à votre question, mais les informations enregistrées ne me permettent pas de l’expliquer de manière fiable. Contactez l’équipe de location avant de continuer.",
    "ask.notFound": "Je n’ai trouvé aucune information enregistrée sur « {question} » pour cette machine. Les dossiers disponibles n’en parlent pas. Demandez à l’équipe de location quoi faire plutôt que de deviner.",
  },
} as const;

export type RenterCopyKey = keyof typeof COPY.en;

export function renterText(language: RenterLanguage, key: RenterCopyKey): string {
  return COPY[language][key];
}

export const RENTER_LANGUAGES: { value: RenterLanguage; label: string; speech: string; name: string }[] = [
  { value: "en", label: "English", speech: "en-US", name: "English" },
  { value: "es", label: "Español", speech: "es-ES", name: "Spanish" },
  { value: "fr", label: "Français", speech: "fr-FR", name: "French" },
];
